apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mediawiki.name" . }}
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ include "mediawiki.name" . }}
  targetCPUUtilizationPercentage: {{ .Values.resources.threshold.cpu }}